name: memories_app
description: memories flutter app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  json_serializable: ^6.6.1
  shared_preferences: ^2.1.0
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login/
    - assets/register/
