name: memories_app
description: memories flutter app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  json_serializable: ^6.6.1
  shared_preferences: ^2.1.0
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  connectivity_plus: ^5.0.1
  golden_toolkit: ^0.15.0
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.1
  timeago: ^3.6.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^1.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  textfield_tags: ^1.4.2
  quill_html_editor: ^2.2.7
  flutter_image_compress: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login/
    - assets/register/
    - assets/landing/
    - assets/home/
