name: Test Flutter

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'mobile/**'
      - '.github/workflows/test_apk.yml'

jobs:
  test_flutter:
    name: test flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.0

      - name: "[CI] Mobile test"
        run: |
          echo
          npm install deers > /dev/null 2>&1
          node -e "const deers = require('deers'); console.log(deers()[new Date().getMinutes()]);" || true
          make
          make test
          ./hack/lcov-coverage.sh

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: mobile/coverage
