name: Test Flutter

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'mobile/**'
      - '.github/workflows/test_apk.yml'

jobs:
  test_flutter:
    name: test flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.0

      - name: Change to "mobile" directory, set up Flutter, and test
        run: |
          echo
          npm install deers > /dev/null 2>&1
          node -e "const deers = require('deers'); console.log(deers()[new Date().getMinutes()]);" || true
          make
          make test
          apt-get update -qq -y && apt-get install -qq -y lcov
          lcov --remove mobile/coverage/lcov.info 'mobile/lib/network/*' -o mobile/coverage/new_lcov.info
          genhtml mobile/coverage/new_lcov.info --output=mobile/coverage
